Repository prgrms-fe-devcourse/FES-5-Project3-TEAM-2, pull requests merged in 2025-08, with the labels that each got.

#22 [chore] 주소 별칭 추가 (#21)
  src/pages/DashBoard/components/PlanList.tsx
  src/pages/DashBoard/components/TripDays.tsx
  src/pages/DashBoard/index.tsx
  tsconfig.app.json
  tsconfig.node.json
  vite.config.ts
Labels: ✨ feature

#32 [feat] 대시보드 통신 api 1차 구현 (#31)
  package-lock.json
  package.json
  src/pages/DashBoard/api/dragUpdate.ts
  src/pages/DashBoard/api/editUpdate.ts
  src/pages/DashBoard/api/insertPlanItem.ts
  src/pages/DashBoard/api/loadGroupData.ts
  src/pages/DashBoard/api/loadPlanItem.ts
  src/pages/DashBoard/utils/createJitter.ts
Labels: ✨ feature

#35 Feat/#12/login
  package-lock.json
  src/assets/icon/google.svg
  src/components/common/Sidebar.tsx
  src/lib/supabaseClient.ts
  src/pages/Group/GroupsPage.tsx
  src/pages/GroupsPage.tsx
  src/pages/Home.tsx
  src/pages/Home/components/LoginCard.tsx
  src/pages/Home/index.tsx
  src/pages/auth/AuthCallback.tsx
  src/router/router.tsx
  src/store/profileStore.ts
  vite.config.ts
Labels: ✨ feature

#37 [feat] 대시보드 일정 리스트 dnd 구현 (#4)
  package-lock.json
  package.json
  src/pages/DashBoard/components/PlanItem.tsx
  src/pages/DashBoard/components/PlanItemOverlay.tsx
  src/pages/DashBoard/components/PlanList.tsx
  src/pages/DashBoard/hooks/useSortableList.ts
Labels: ✨ feature

#52 [feat] 대시보드 CRUD 통신 구현 (#6, #38)
  src/assets/icons/confirm_icon.png
  src/pages/DashBoard/api/deletePlanItem.ts
  src/pages/DashBoard/api/dragUpdate.ts
  src/pages/DashBoard/api/editUpdate.ts
  src/pages/DashBoard/api/insertPlanItem.ts
  src/pages/DashBoard/api/loadPlanItem.ts
  src/pages/DashBoard/components/AddPlanItemModal.tsx
  src/pages/DashBoard/components/PlanItem.tsx
  src/pages/DashBoard/components/PlanItemOverlay.tsx
  src/pages/DashBoard/components/PlanList.tsx
  src/pages/DashBoard/components/TripDays.tsx
  src/pages/DashBoard/components/TripInfo.tsx
  src/pages/DashBoard/hooks/useSortableList.ts
  src/pages/DashBoard/store/groupStore.ts
  src/pages/DashBoard/store/planStore.ts
  src/pages/DashBoard/utils/createJitter.ts
  src/pages/DashBoard/utils/generateTripDays.ts
  src/router/loader/dashBoardLoader.ts
  src/router/router.tsx
Labels: ✨ feature

#57 [fix] 지터 타입 오류 수정 (#null)
  src/pages/DashBoard/api/dragUpdate.ts
  src/pages/DashBoard/api/editUpdate.ts
  src/pages/DashBoard/api/insertPlanItem.ts
  src/pages/DashBoard/api/loadPlanItem.ts
  src/types/supabase.d.ts
Labels: 🐞bug

#58 [feat] 예산 페이지 기능 구현
  src/components/common/Button.tsx
  src/lib/supabaseClient.ts
  src/pages/Budget/api/expenses.ts
  src/pages/Budget/components/AddExpenseModal.tsx
  src/pages/Budget/components/BudgetStatsCard.tsx
  src/pages/Budget/components/ExpenseList.tsx
  src/pages/Budget/components/SettlementPanel.tsx
  src/pages/Budget/index.tsx
  src/pages/auth/AuthCallback.tsx
  src/router/router.tsx
  src/store/budgetStore.ts
  src/types/supabase.d.ts
Labels: ✨ feature, 🎨 design, 🐞bug

#62 [feat] 웹소켓 postgres_changes 구현
  src/pages/DashBoard/api/loadGroupData.ts
  src/pages/DashBoard/index.tsx
  src/pages/DashBoard/store/planStore.ts
Labels: ✨ feature

#68 [feat] 대시보드 웹소켓 공동 편집 구현 (#8)
  src/components/common/Sidebar.tsx
  src/pages/DashBoard/api/getMyProfile.ts
  src/pages/DashBoard/api/getMyUserId.ts
  src/pages/DashBoard/components/PlanItem.tsx
  src/pages/DashBoard/index.tsx
  src/pages/DashBoard/store/planStore.ts
  src/pages/DashBoard/store/presenceStore.ts
  src/pages/Group/api/getGroupMembers.ts
  src/pages/Group/components/GroupMemberList.tsx
  src/pages/Group/hooks/useGroupMembers.ts
  src/pages/Group/utils/colorUtils.ts
  src/router/loader/dashBoardLoader.ts
  src/types/supabase.d.ts
Labels: ✨ feature
