Repository prgrms-fe-devcourse/FES-5-Project3-TEAM-2, pull requests merged in 2025-09, with the labels that each got.

#75 [ui] 예산 스크롤바 스타일, 사이드바 아이콘 색 수정
  src/components/common/Sidebar.tsx
  src/pages/Budget/components/ExpenseList.tsx
  src/pages/Budget/index.tsx
Labels: 🎨 design

#80 [ui] 대시보드 ui 피드백 2차 수정 (#null)
  src/components/common/Sidebar.tsx
  src/pages/DashBoard/components/PlanItemOverlay.tsx
  src/pages/DashBoard/components/PlanList.tsx
  src/pages/DashBoard/components/Schedule.tsx
  src/pages/DashBoard/components/TripDays.tsx
  src/pages/DashBoard/components/TripInfo.tsx
  src/pages/DashBoard/index.tsx
Labels: ✨ feature

#82 [ui] 로그인페이지 애니메이션 수정
  src/pages/Home/index.tsx
Labels: 🎨 design

#83 [fix] 나의 접속 여부 제거 (#null)
  src/pages/DashBoard/api/dragUpdate.ts
  src/pages/DashBoard/index.tsx
Labels: 🐞bug

#88 [ui] 사이드바 아이콘 색 수정
  src/components/common/Sidebar.tsx
Labels: 🎨 design

#107 [refactor] 지도 리렌더링 방지
  src/pages/DashBoard/components/Map.tsx
  src/pages/DashBoard/components/MapContainer.tsx
  src/pages/DashBoard/index.tsx
Labels: 🛠 refactor

#109 [Refactor] 배경사진 업데이트 시 누적 방지
  src/pages/Group/components/AlbumPickModal.tsx
  src/pages/Group/components/GroupCard.tsx
  src/pages/Group/utils/storagePublicUrl.ts
Labels: 🛠 refactor

#118 [ui] 로그인페이지 반응형 대응
  src/pages/Home/components/HomeSections.tsx
  src/pages/Home/components/LoginCard.tsx
  src/pages/Home/index.tsx
Labels: 🎨 design

#119 [ui] 예산페이지 반응형 대응
  src/pages/Budget/components/BudgetStatsCard.tsx
  src/pages/Budget/index.tsx
Labels: 🎨 design

#122 [ui] 대시보드 반응형 대응 (#121)
  src/pages/DashBoard/components/PlanItem.tsx
  src/pages/DashBoard/components/TripDays.tsx
  src/pages/DashBoard/index.tsx
Labels: 🎨 design

#125 [Feature ] 로그인 페이지 애니메이션 추가
  src/pages/DashBoard/components/SearchBox.tsx
  src/pages/DashBoard/components/SearchResults.tsx
  src/pages/Home/components/LoginCard.tsx
  src/pages/Home/index.tsx
Labels: 🎨 design

#126 [ui] 예산페이지 잘리는 문제 수정
  src/pages/Budget/index.tsx
Labels: 🐞bug
